version: "3.8"
services:
  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache-container
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 532532Se1cretPassword_IsImportant43243
      MYSQL_DATABASE: badcrud
    ports:
      - "3306:3306"
    volumes:
      - ./app/db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro